.POSIX:

ar.o: ar/ar.c
asa.o: asa/asa.c
basename.o: basename/basename.c
bc.o:// bc/bc.c
cal.o: cal/cal.c
cat.o: cat/cat.c
chgrp.o: chgrp/chgrp.c
chmod.o: chmod/chmod.c
chown.o: chown/chown.c
cksum.o: cksum/cksum.c
cmp.o: cmp/cmp.c
cp.o: cp/cp.c
crontab.o: crontab/crontab.c
ctags.o: ctags/ctags.c
date.o: date/date.c
dd.o: dd/dd.c
dirname.o: dirname/dirname.c
du.o: du/du.c
ed.o: ed/ed.c
ed.o: ed/commands.c
ed.o: ed/env.c
ed.o: ed/input.c
ed.o: ed/io.c
ed.o: ed/re.c
ed.o: ed/signals.c
ed.o: ed/stubs.c
env.o: env/env.c
ex.o: ex/ex.c
expand.o: expand/expand.c
file.o: file/file.c
file.o: file/magic.c
getconf.o: getconf/getconf.c
grep.o: grep/grep.c
head.o: head/head.c
iconv.o: iconv/iconv.c
id.o: id/id.c
link.o: link/link.c
ln.o: ln/ln.c
locale.o: locale/locale.c
logger.o: logger/logger.c
logname.o: logname/logname.c
ls.o: ls/ls.c
mkdir.o: mkdir/mkdir.c
mkfifo.o: mkfifo/mkfifo.c
more.o: more/more.c
nice.o: nice/nice.c
nohup.o: nohup/nohup.c
od.o: od/od.c
paste.o: paste/paste.c
pathchk.o: pathchk/pathchk.c
printf.o: printf/printf.c
renice.o: renice/renice.c
rm.o: rm/rm.c
rmdir.o: rmdir/rmdir.c
sh.o: mains.h
sh.o: builtins.h
sh.o: sh/alias.c
sh.o: sh/bg.c
sh.o: sh/builtins.c
sh.o: sh/cd.c
sh.o: sh/command.c
sh.o: sh/dot.c
sh.o: sh/eval.c
sh.o: sh/exec.c
sh.o: sh/exit.c
sh.o: sh/export.c
sh.o: sh/false.c
sh.o: sh/fc.c
sh.o: sh/fg.c
sh.o: sh/getopts.c
sh.o: sh/hash.c
sh.o: sh/init.c
sh.o: sh/interactive.c
sh.o: sh/jobs.c
sh.o: sh/kill.c
sh.o: sh/main.c
sh.o: sh/newgrp.c
sh.o: sh/parse.c
sh.o: sh/pwd.c
sh.o: sh/read.c
sh.o: sh/readonly.c
sh.o: sh/set.c
sh.o: sh/sh.tab.c
sh.o: sh/sh.yy.c
sh.o: sh/shift.c
sh.o: sh/times.c
sh.o: sh/trap.c
sh.o: sh/true.c
sh.o: sh/type.c
sh.o: sh/ulimit.c
sh.o: sh/umask.c
sh.o: sh/unset.c
sh.o: sh/wait.c
sleep.o: sleep/sleep.c
split.o: split/split.c
strings.o: strings/strings.c
stty.o: stty/stty.c
tail.o: tail/tail.c
tee.o: tee/tee.c
tput.o: tput/tput.c
tr.o: tr/tr.c
uname.o: uname/uname.c
unlink.o: unlink/unlink.c
uudecode.o: uudecode/uudecode.c
uuencode.o: uuencode/uuencode.c
wc.o: wc/wc.c
who.o: who/who.c
write.o: write/write.c
