#define EXTRA_BUILTINS \
	{ "ar", ar_main }, \
	{ "asa", asa_main }, \
	{ "basename", basename_main }, \
	{ "cal", cal_main }, \
	{ "cat", cat_main }, \
	{ "chgrp", chgrp_main }, \
	{ "chmod", chmod_main }, \
	{ "chown", chown_main }, \
	{ "cksum", cksum_main }, \
	{ "cmp", cmp_main }, \
	{ "cp", cp_main }, \
	{ "crontab", crontab_main }, \
	{ "ctags", ctags_main }, \
	{ "date", date_main }, \
	{ "dd", dd_main }, \
	{ "dirname", dirname_main }, \
	{ "du", du_main }, \
	{ "ed", ed_main }, \
	{ "env", env_main }, \
	{ "ex", ex_main }, \
	{ "expand", expand_main }, \
	{ "file", file_main }, \
	{ "getconf", getconf_main }, \
	{ "grep", grep_main }, \
	{ "head", head_main }, \
	{ "iconv", iconv_main }, \
	{ "id", id_main }, \
	{ "link", link_main }, \
	{ "ln", ln_main }, \
	{ "locale", locale_main }, \
	{ "logger", logger_main }, \
	{ "logname", logname_main }, \
	{ "ls", ls_main }, \
	{ "mkdir", mkdir_main }, \
	{ "mkfifo", mkfifo_main }, \
	{ "more", more_main }, \
	{ "nice", nice_main }, \
	{ "nohup", nohup_main }, \
	{ "od", od_main }, \
	{ "paste", paste_main }, \
	{ "pathchk", pathchk_main }, \
	{ "printf", printf_main }, \
	{ "renice", renice_main }, \
	{ "rm", rm_main }, \
	{ "rmdir", rmdir_main }, \
	{ "sleep", sleep_main }, \
	{ "split", split_main }, \
	{ "strings", strings_main }, \
	{ "stty", stty_main }, \
	{ "sum", sum_main }, \
	{ "tail", tail_main }, \
	{ "tee", tee_main }, \
	{ "tput", tput_main }, \
	{ "tr", tr_main }, \
	{ "uname", uname_main }, \
	{ "unlink", unlink_main }, \
	{ "uudecode", uudecode_main }, \
	{ "uuencode", uuencode_main }, \
	{ "wc", wc_main }, \
	{ "who", who_main }, \
	{ "write", write_main },
